[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = false
port = 8501

[browser]
gatherUsageStats = false

# Vehicle Router App Configuration
# Configure which optimization models are available in the web application

[app.models.standard]
name = "📊 Standard MILP + Greedy"
description = "Two-phase hybrid optimization: cost-optimal truck selection + route sequence optimization"
help = "Fast, cost-optimal with distance-optimized routes. Best for daily operations."
enabled = true
default_depot_return = false
default_greedy_routes = true

[app.models.enhanced]
name = "🚀 Enhanced MILP"  
description = "Multi-objective MILP with simultaneous cost-distance optimization and routing variables"
help = "Globally optimal multi-objective solutions. Higher computational cost."
enabled = false  # Hidden by default - advanced users only
default_depot_return = false
default_cost_weight = 0.6
default_distance_weight = 0.4

[app.models.genetic]
name = "🧬 Genetic Algorithm"
description = "Evolutionary metaheuristic with population-based search and genetic operators"
help = "Balanced cost-distance optimization. Excellent for large problems."
enabled = true
default_depot_return = false
default_population_size = 50
default_max_generations = 100
default_mutation_rate = 0.1
fixed_cost_weight = 0.5  # Fixed balanced weighting
fixed_distance_weight = 0.5

# Distance calculation configuration
[app.distances]
default_method = "simulated"  # Options: "simulated" or "real_world"
simulated_description = "Mathematical approximation: 1km per postal code unit difference"
real_world_description = "OpenStreetMap geocoding + Haversine great-circle distance calculation"
geocoding_provider = "openstreetmap"
default_country_code = "ES"
rate_limit_seconds = 0.5
cache_enabled = true

# Application behavior settings
[app.behavior]
auto_load_example_data = false
show_progress_indicators = true
enable_solution_validation = true
default_solver_timeout = 60
max_solver_timeout = 300

# UI customization
[app.ui]
show_method_documentation = true  # Show documentation after optimization
show_distance_heatmap = true
show_route_visualizations = true
enable_excel_export = true
default_depot_location = "08020"

# Performance settings
[app.performance]
max_orders_for_enhanced_milp = 50  # Performance recommendation
max_orders_per_truck_greedy = 8   # Factorial complexity limit
recommended_ga_population_large = 100  # For 50+ orders